language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"
before_script:
    # ssh login on localhost
    - ssh-keygen -f ~/.ssh/id_rsa -N ""
    - cp ~/.ssh/{id_rsa.pub,authorized_keys}
script:
    - cd ..
    - python -munittest pretzel
