language: python

python:
    - 2.7
    - 3.2
    - 3.3
    - pypy

env:
    - PRETZEL_TEST_TIMEOUT=30 # pypy takes longer to start

install:
    - pip install coveralls --use-mirrors
    - pip install greenlet --use-mirrors

before_script: |
    ssh-keygen -R localhost
    ssh-keygen -f ~/.ssh/id_rsa -N ""
    cp ~/.ssh/{id_rsa.pub,authorized_keys}
    netstat -tan | grep LISTEN
    ssh -v -oBatchMode=yes -oStrictHostKeyChecking=no localhost true

script: |
    cd ..
    export PYTHONPATH=`pwd`
    if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then
        cp pretzel/.coveragerc ./
        coverage run -m unittest pretzel
        coverage run -a -m pretzel.bench
        coverage report
        cp .coverage pretzel
    else
        python -m unittest pretzel
        python -m pretzel.bench
    fi
    cd pretzel

after_success: |
    if [[ -f .coverage ]]; then
        coveralls
    fi

notifications:
    email: false
