language: python
python:
    - 2.7
    - 3.2
    - 3.3
    - pypy
env:
    # pypy takes longer to start
    - PRETZEL_TEST_TIMEOUT=30
install:
    pip install coveralls --use-mirrors
before_script:
    # ssh login on localhost
    - ssh-keygen -f ~/.ssh/id_rsa -N ""
    - cp ~/.ssh/{id_rsa.pub,authorized_keys}
script:
    - cd ..
    - python -mpretzel.tests -c
    # do not run coverage on pypy
    - "if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then python -mpretzel.tests -c; else python -mpretzel.tests; fi"
    - "test -f .coverage && mv .coverage pretzel || true"
    - cd pretzel
after_success:
    "test -f .coverage && coveralls"
notifications:
    email: false
