language: python
python:
    - 2.7
    - 3.2
    - 3.3
    - pypy
env:
    # pypy takes longer to start
    - PRETZEL_TEST_TIMEOUT=30
install:
    - pip install coveralls --use-mirrors
    - pip install greenlet --use-mirrors
before_script:
    - "netstat -tan | grep LISTEN"
    - "ssh -oBatchMode=yes localhost true"
script:
    - cd ..
    - cp pretzel/.coveragerc ./
    # do not run coverage on pypy
    - "if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then coverage run -m unittest pretzel; else python -m unittest pretzel; fi"
    - "test -f .coverage && coverage report && mv .coverage pretzel || true"
    - cd pretzel
after_success:
    "test -f .coverage && coveralls || true"
notifications:
    email: false
